# Generated by Django 3.2 on 2021-04-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codechef_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='codechef_id',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='prn',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='role_id',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
