# Generated by Django 3.2 on 2021-04-25 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codechef_management_app', '0003_events_people'),
    ]

    operations = [
        migrations.DeleteModel(
            name='People',
        ),
    ]
