# Generated by Django 3.2 on 2021-04-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codechef_management_app', '0005_auto_20210425_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role_id',
            field=models.CharField(default='3', max_length=1),
        ),
    ]
