# Generated by Django 3.2 on 2021-04-27 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codechef_management_app', '0007_user_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role_id',
        ),
    ]
