# Generated by Django 3.2 on 2021-04-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codechef_management_app', '0008_remove_user_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_date',
            field=models.DateField(),
        ),
    ]
