# Generated by Django 3.2 on 2021-04-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codechef_management_app', '0009_auto_20210427_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='codechef_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
